services:
  nginx:
    build: ./nginx/
    container_name: nginx
    networks:
      - inception
    ports:
      - "443:443"
      # - "80:80" # TODO: DELETE THIS
    restart: unless-stopped
    env_file: .env

  mariadb:
    build: ./mariadb/
    container_name: mariadb
    networks:
      - inception
    restart: unless-stopped
    env_file: .env

  wordpress:
    build: ./wordpress/
    container_name: wordpress
    # required:
    #   - mariadb
    networks:
      - inception
    restart: unless-stopped
    env_file: .env

networks:
  inception:
    name: inception
